# Generated by Django 3.2.9 on 2021-11-09 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emploapp', '0003_stud_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud',
            name='owner',
        ),
    ]
