# Generated by Django 3.2.9 on 2021-11-12 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emploapp', '0008_employee_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud',
            name='owner',
        ),
    ]
