# Generated by Django 3.2.9 on 2021-11-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploapp', '0010_stud_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='cust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('product', models.CharField(max_length=10)),
                ('cust_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='owner',
        ),
    ]
