# Generated by Django 3.2.9 on 2021-11-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emploapp', '0011_auto_20211112_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud',
            name='owner',
        ),
    ]
